### ISSUE TITLE
Need package with the latest changes

### ISSUE THREAD

**Issue by DannySantos** [jimmywarting/FormData#101]
The npm package doesn't seem to have the most recent changes regarding the treating of data as an array, is there a way we can get those changes into our project?

**Comment by jimmywarting** [comment]
Hi @DannySantos are you still interested in having me to bump a new version?

treating the underlying source as an array instead of an object just changes the order in how they are processed. But i thought it didn't have any big valuable inpack on anyones code so i thought i would just ship it with the next fix of whatever i do. but it dosen't seem to be anything left to do to formdata-polyfill 🙃
