### ISSUE TITLE
Example in the readme is confusing

### ISSUE THREAD

**Issue by GrosSacASac** [jimmywarting/FormData#141]
The following line:
```js
fd.append('file-upload', new File(['abc'], 'hello-world.txt'))
```
I thought I would stream the file hello-world.txt

**Comment by jimmywarting** [comment]
- FormData can't accept a stream
- FormData can only accept 3 things... String, Blob and File
- FormData Also needs to be able to calculate the total `content-length` in adv, so that's why it only accepts file & blobs with a known size property.

so the way you would actually stream a file is that you would somehow get a File class from the filesystem that would stream the file for you.

the file class itself has a [File.prototype.stream()](https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream) method that we will call to read the file

---

so you wouldn't actually stream the file into a formdata, we read the data for you...

**Comment by jimmywarting** [comment]
NodeJS is plaining on implementing a method to get Blob/Files from the filesystem somehow
but in the meantime you would need something like: https://github.com/node-fetch/fetch-blob#blob-part-backed-up-by-filesystem

**Comment by jimmywarting** [comment]
The File class is also constructible, so you can create files in memory

**Comment by GrosSacASac** [comment]
Thanks for the details
