### ISSUE TITLE
Add File Upload support to README

### ISSUE THREAD

**Issue by odahcam** [jimmywarting/FormData#70]
I can't find what are the file upload supported IE versions, so I think it would be nice to list on README what IE versions will be able to upload files, something like that:

- IE6: FormData - file upload disabled
- IE8: FormData - file upload through iframe and blob.js
- IE10: FormData - file upload with FormData

That's not real data, but something like that or a table would be nice.

**Comment by jimmywarting** [comment]
lol, IE6 is it really worth to mention? it has been dead a long time now. Anyone building something for ie6 are wasting there time.

but yea, i know what you are after. 
can write something down

**Comment by odahcam** [comment]
Well, you should know that people searching for polyfills usually wants to do very strange things, you would be surprised with some of the intentions. 😄

Your solution seems very nice, that's already useful for me.

**Comment by jimmywarting** [comment]
It's kinda already in the readme

> If you need to support IE <= 9 then I recommend you to include eligrey's blob.js

seems pointless to change the readme just for that

**Comment by odahcam** [comment]
> If you need to support IE <= 9

What's the earlier version of IE I can use with the polyfill?

**Comment by jimmywarting** [comment]
FormData-polyfill depends on Blob support. IE10 is the first version that has support for blobs but they also shipped a partial FormData implementation. It's limited to only using the `constructor` and `append` so it's incomplete. So unless you don't need to edit or read the content of the FormData then the partial implementation of the native FormData can be used instead of the polyfill.

however if you include both elgray's blob.js and my formdata polyfill you might be able to use IE7 (haven't tested - always working on a Mac)

I think both scripts are written so it support EcmaScript 3 (1999)

But I wouldn't stretch that far as to include blob.js
IE8-9 combined marketshare is only 0.69
and IE10 is not even on the chart

![skarmavbild 2019-02-01 kl 18 30 56](https://user-images.githubusercontent.com/1148376/52139210-c3289780-264f-11e9-8e16-e083d4cd6179.png)

http://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201901-201901-bar

**Comment by odahcam** [comment]
Thanks, that's great info. 

I know about the IE presence in the web, but it occurs that when you enter in enterprise with +15k employee you may find some curious stuff like IE8 being the default browser for everyone. In that case you end up with ~180 simultaneous IE6 to IE10 connections to a web app. A nightmare you think? Yes it is.

It already answered my questions, but I'll keep it open in case you wanna add more info like your last comment to the README or just close it. Thank you very much for your help.
