### ISSUE TITLE
Support Node.js environment

### ISSUE THREAD

**Issue by jaydenseric** [jimmywarting/FormData#72]
In Node.js (in `--experimental-modules` mode, not that it's relevant to the issue):

```js
import 'formdata-polyfill'
```

Results in:

```
ReferenceError: Blob is not defined
    at [redacted]/node_modules/formdata-polyfill/formdata.min.js:9:425
    at Object.<anonymous> ([redacted]/node_modules/formdata-polyfill/formdata.min.js:17:3)
```

**Comment by jimmywarting** [comment]
I have fought about it before.
Reason why I haven't done it yet is because [form-data](https://www.npmjs.com/package/form-data) is available for node and it supports streams. wish is not part of the formData api. and i don't feel like i want to create yet another npm module.
it's important for backend to support streams if you want to be able to handle many and large requests

**Comment by jaydenseric** [comment]
At the very least, for SSR purposes importing the polyfill should not crash in a Node.js environment. Next.js users could not use this package for example.

**Comment by jimmywarting** [comment]
> At the very least, for SSR purposes importing the polyfill should not crash in a Node.js environment.

Done and publish, that is the least I can do. 

I leave this issue open, if ppl don't want to use form-data and if i get at least a few 👍 i might implement a NodeJS version that use Buffer/Streams and doesn't use Blob, fetch or XMLHttpRequest - it will be up to the libraries to support my polyfill then.
